### ISSUE TITLE
attempt to index global 'static_tbl' (a nil value)

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#25]
This is a remnant of #23. It happens in LEVEL1.lua and GYM.lua. Levels are loading but eventually will crash.

**Comment by Lwmte** [comment]
Seems that in case of GYM.PHD, it was trashed red-black tree, which was cleared before game loop was finished. I fixed this by moving Gameflow_Do function out of game loop right to the end of main loop. Also I fixed some other level crashes by extending script buffer. Please check if you still have crashes!

**Comment by vvs-** [comment]
No crashes anymore. But the error is still there of course, albeit a cosmetic one. There are still leftovers of static_tbl in these scripts.

**Comment by Lwmte** [comment]
Ok, I guess I'll bring back static mesh script, since some bounding boxes in original TRs produce awkward standing collision, but collision override will be done only for such statics.

**Comment by Lwmte** [comment]
Static mesh script is brought back with some small changes, also I still force bounding box, in case corresponding table entry is empty.
